# Generated by Django 2.2 on 2019-04-10 20:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20190409_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.FileField(default=datetime.datetime(2019, 4, 10, 20, 17, 27, 767960, tzinfo=utc), upload_to=''),
            preserve_default=False,
        ),
    ]
